### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by stvedo** [nsftx/incubator-2019-rating-app#4]
Replace **underscore** npm package with **lodash** package, since there are high security issues in project.

Upgrade constantinople to version 3.1.1 or later. For example:
```
"dependencies": {
  "constantinople": ">=3.1.1"
}
```
or…
```
"devDependencies": {
  "constantinople": ">=3.1.1"
}
```

Upgrade clean-css to version 4.1.11 or later. For example:
```
"dependencies": {
  "clean-css": ">=4.1.11"
}
```
or…
```
"devDependencies": {
  "clean-css": ">=4.1.11"
}
```

**Comment by darijan92** [comment]
I replaced underscore with lodash package.
Other 2 packages can't be upgraded since they are not installed in our project. 
Should we install them? I don't see where would I use clean-css.

**Comment by darijan92** [comment]
Dependencies updated.
